### ISSUE TITLE
HTML editor needs maximize button and should remember size

### ISSUE THREAD

**Issue by dae** [ankitects/help-wanted#1]
aqt.utils.saveGeom/restoreGeom can be used to remember size

original report: https://anki.tenderapp.com/discussions/ankidesktop/41780-html-editor-in-need-of-a-maximize-button

**Comment by sandersantema** [comment]
Possibly partially fixed: https://github.com/ankitects/anki/pull/638

**Comment by dae** [comment]
Thanks for helping out!

**Comment by lingocoder** [comment]
@dae? @sandersantema? What ever happened with this?

I stumbled across this issue through [*a search of the discussion forums*](https://anki.tenderapp.com/discussions/ankidesktop/41780-html-editor-in-need-of-a-maximize-button).

I run *Version 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1* on Windows. And the HTML editor *still* does not have a maximize button:

![anki html editor 0](https://user-images.githubusercontent.com/49788472/90981245-c5b35080-e557-11ea-9d52-5dfbb1ff6eef.png)

Is there *at least* a config file somewhere in the Anki installation location, that I can edit to make the HTML editor window open up maximized?

TIA.

**Comment by ANH25** [comment]
> I run _Version 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1_ on Windows. And the HTML editor _still_ does not have >  a maximize button:

I think the change was introduced in version 2.1.28

**Comment by lingocoder** [comment]
@dae? What's the rationale for not listing [*the release notes*](https://github.com/ankitects/anki/releases/) on [*the main project page*](https://github.com/ankitects/anki).

Currently, the only way to find them is to search the web. Since the project's main page is the most obvious place users would expect to find things like release notes, it would be more convenient if they were linked to there. No?
