### ISSUE TITLE
Investigate sizing issues when using UI scale

### ISSUE THREAD

**Issue by dae** [ankitects/help-wanted#18]
The size appears to be doubled without a corresponding increase in font size:

https://forums.ankiweb.net/t/huge-margins-when-100-iu/2432

**Comment by androidpcguy** [comment]
I'll take a look at this issue

**Comment by androidpcguy** [comment]
I've been playing around with the UI size option in the Preferences, but I'm not seeing any visual changes (other than that annoying extra bottom space) between 100% and 200% even after restarting, including any changes to font size. That space also exists on views that have a bottom bar. What is the expected behavior of this option? I've attached some screenshots of the main window at 100% and 200% scaling. Perhaps this scaling option can be replaced with a proper font picker?

100% scale:
![image](https://user-images.githubusercontent.com/11450337/94943324-84428900-04a5-11eb-90cd-7f84400bcc6d.png)

200% scale:
![image](https://user-images.githubusercontent.com/11450337/94943375-9cb2a380-04a5-11eb-851b-15bcc1f37998.png)

**Comment by androidpcguy** [comment]
Okay, think I found the issue and fixed it. Submitting a PR soon

**Comment by androidpcguy** [comment]
Oh I see, that makes sense, thanks for explaining
